language: php
php:
- 5.4
- 5.5
- 5.6
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
notifications:
  slack:
    secure: hXEMjPtNQDdlFV1kb5uHhpPW22tgyI0v9gT/lyTsMOAvA/UTRhDWq96FR3dD88WmRI5AZYk/zlqpYDgy6/QU92OVI87dnPTd2KQ9Zi5SpEpENsnlnnGMxaXdtSuMbYGFjD0A3i7U98HiMLYr6W2R0Y3Ok0lJXVZnq7wL1sSiBe5jCORZJ2lHiyyOCM86NJM59MvZOD0FtGg4nqJtLYdG63P7gPgav+U0vm8Fsdmp6BhyvnoWeli3Py66CO54OJUGn9FjbuGfnJ6Re+uJx1B3OZXAG3Q16BwL3u+dXM+JNhwsKxmEnIUMSfGop8yIxyAJtW9e9Vn54Rlt/V61rqIvwSumkHR4+f+91BcCWhJ6DfCxKF1RE+T3R2zT5tH/W3cvsw5mTE6Sc12uKdFOfwf9PqH/skUjJAuDDeHVxUysd8dkmmJc3QaX2K4MFxzK4ACMuu4q4DzpJO2DCc4y6DtBkJaD/1Win/XnZdEiO+paW0eZxGFcMuMwXRk1T9AinchEA0tY2sxvLspgQcd/cG3Tuv3OZp52SzRa1l7pVyawPrF/42DMFiUJtOeYCDUPRellFGT0MVg5OX32nNAueeg58QVaGCkneNBE0GwG/7RycHNw4dwhOn6TfCQ4FhzghKSe7vvinzoM4MOxyI+0Q4aLfnUm1zgOiwY045AzS1Yz0A0=
